(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Standard Model",
  Authors -> {"N. Christensen", "C. Duhr", "B. Fuks"},
  Version -> "1.4.7",
  Date -> "28. 09. 2016",
  Institutions -> {"Michigan State University", "Universite catholique de Louvain (CP3)", "IPHC Strasbourg / University of Strasbourg"},
  Emails -> {"neil@pa.msu.edu", "claude.duhr@uclouvain.be", "benjamin.fuks@cnrs.in2p3.fr"},
  URLs -> "http://feynrules.phys.ucl.ac.be/view/Main/StandardModel"};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], Aux -> V[5], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], x -> F[13], H -> S[1], G0 -> S[2], GP -> S[3]};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

V[5] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> Lambda,
    Indices -> {},
    PropagatorLabel -> "Aux" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MMU,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

F[13] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mx,
    Indices -> {},
    PropagatorLabel -> "x" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ F[13] ] = GaugeXi[F[5]];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Lambda[ ___ ] := Lambda;
Me[ ___ ] := Me;
MMU[ ___ ] := MMU;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
mx[ ___ ] := mx;
MH[ ___ ] := MH;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] , V[5] ] == {{(-2*I)*CH*EL, 0}},

C[ S[2] , S[1] , V[5] ] == {{-gc12, 0}, {gc12, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc13, 0}, {I*gc13, 0}},

C[ S[3] , -S[3] , V[5] ] == {{(-I)*gc14, 0}, {I*gc14, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc15, 0}, {I*gc15, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc16, 0}, {I*gc16, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc18, 0}, {I*gc18, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-I/4)*EL^2*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc21, 0}, {I*gc21, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc22, 0}, {I*gc22, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc24, 0}, {I*gc24, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc26, 0}, {I*gc26, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-I/4)*EL^2*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc29, 0}, {I*gc29, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc30, 0}, {I*gc30, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc32, 0}, {I*gc32, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc34, 0}, {I*gc34, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc36, 0}, {I*gc36, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/4)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -F[13] , F[13] , S[2] , S[2] ] == {{(-I)*(CP - CS), 0}, {I*(CP + CS), 0}},

C[ -F[13] , F[13] , S[3] , -S[3] ] == {{(-I)*(CP - CS), 0}, {I*(CP + CS), 0}},

C[ -F[13] , F[13] , S[1] , S[1] ] == {{(-I)*(CP - CS), 0}, {I*(CP + CS), 0}},

C[ -F[13] , F[13] , S[1] ] == {{I*gc41L, 0}, {I*gc41R, 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc42*SUNF[e3x2, e1x1, e2x1], 0}, {gc42*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc43*SUNF[e1x2, e2x2, e3x2]), 0}, {gc43*SUNF[e1x2, e2x2, e3x2], 0}, {gc43*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc43*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc43*SUNF[e1x2, e2x2, e3x2]), 0}, {gc43*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc44*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc44*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc44*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[13] , F[13] , V[5] ] == {{I*gc45L, 0}, {I*gc45R, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc46L*IndexDelta[e1x2, e2x2], 0}, {gc46R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc47L*IndexDelta[e1x2, e2x2], 0}, {gc47R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc48L*IndexDelta[e1x2, e2x2], 0}, {gc48R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc49L*IndexDelta[e1x2, e2x2], 0}, {gc49R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc50L*IndexDelta[e1x2, e2x2], 0}, {gc50R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc51L*IndexDelta[e1x2, e2x2], 0}, {gc51R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc52L*IndexDelta[e1x2, e2x2], 0}, {gc52R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc53L*IndexDelta[e1x2, e2x2], 0}, {gc53R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc54L*IndexDelta[e1x2, e2x2], 0}, {gc54R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc55L*IndexDelta[e1x2, e2x2], 0}, {gc55R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{gc56L*IndexDelta[e1x2, e2x2], 0}, {gc56R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{gc57L*IndexDelta[e1x2, e2x2], 0}, {gc57R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc58*IndexDelta[e1x2, e2x2], 0}, {I*gc58*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc59*IndexDelta[e1x2, e2x2], 0}, {I*gc59*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc60*IndexDelta[e1x2, e2x2], 0}, {I*gc60*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[1] , -S[3] ] == {{gc61, 0}, {0, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{gc62, 0}, {0, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{gc63, 0}, {0, 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc64L, 0}, {gc64R, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc65L, 0}, {gc65R, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc66L, 0}, {gc66R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc67, 0}, {I*gc67, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc68, 0}, {I*gc68, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc69, 0}, {I*gc69, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc70L*IndexDelta[e1x2, e2x2], 0}, {gc70R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc71L*IndexDelta[e1x2, e2x2], 0}, {gc71R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc72L*IndexDelta[e1x2, e2x2], 0}, {gc72R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc73L*IndexDelta[e1x2, e2x2], 0}, {gc73R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc74L*IndexDelta[e1x2, e2x2], 0}, {gc74R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc75L*IndexDelta[e1x2, e2x2], 0}, {gc75R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc76L*IndexDelta[e1x2, e2x2], 0}, {gc76R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc77L*IndexDelta[e1x2, e2x2], 0}, {gc77R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc78L*IndexDelta[e1x2, e2x2], 0}, {gc78R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{gc79L*IndexDelta[e1x2, e2x2], 0}, {gc79R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc80L*IndexDelta[e1x2, e2x2], 0}, {gc80R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{gc81L*IndexDelta[e1x2, e2x2], 0}, {gc81R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc82*IndexDelta[e1x2, e2x2], 0}, {I*gc82*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc83*IndexDelta[e1x2, e2x2], 0}, {I*gc83*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc84*IndexDelta[e1x2, e2x2], 0}, {I*gc84*IndexDelta[e1x2, e2x2], 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-EL^2/(2*sw), 0}},

C[ -S[3] , V[1] , V[3] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc88, 0}, {I*gc88, 0}},

C[ -S[3] , S[1] , V[3] ] == {{-gc89, 0}, {gc89, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc90, 0}, {I*gc90, 0}, {I*gc90, 0}, {(-I)*gc90, 0}, {(-I)*gc90, 0}, {I*gc90, 0}},

C[ S[2] , -S[3] , V[5] , V[3] ] == {{(I*CH*EL)/sw, 0}},

C[ -S[3] , S[1] , V[5] , V[3] ] == {{(CH*EL)/sw, 0}},

C[ -S[3] , V[5] , V[3] ] == {{(CH*EL*vev)/sw, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc97, 0}, {I*gc97, 0}},

C[ S[3] , S[1] , -V[3] ] == {{-gc98, 0}, {gc98, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc103, 0}, {(-I)*gc103, 0}, {(2*I)*gc103, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc104, 0}, {I*gc104, 0}, {I*gc104, 0}, {(-I)*gc104, 0}, {(-I)*gc104, 0}, {I*gc104, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc105, 0}, {(-I)*gc105, 0}, {(2*I)*gc105, 0}},

C[ S[2] , S[3] , V[5] , -V[3] ] == {{(I*CH*EL)/sw, 0}},

C[ S[3] , S[1] , V[5] , -V[3] ] == {{-((CH*EL)/sw), 0}},

C[ S[3] , V[5] , -V[3] ] == {{-((CH*EL*vev)/sw), 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0}, {gc109R, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0}, {gc110R, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc111R, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc113, 0}, {gc113, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc114, 0}, {I*gc114, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-EL^2/(2*cw), 0}},

C[ S[3] , -V[3] , V[2] ] == {{-(EL^2*vev)/(2*cw), 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc121, 0}, {I*gc121, 0}, {I*gc121, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc126, 0}, {(-I)*gc126, 0}, {(2*I)*gc126, 0}},

C[ S[2] , S[2] , V[5] , V[2] ] == {{(I*CH*EL*(cw^2 + sw^2))/(cw*sw), 0}},

C[ S[3] , -S[3] , V[5] , V[2] ] == {{((-I)*CH*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[1] , S[1] , V[5] , V[2] ] == {{(I*CH*EL*(cw^2 + sw^2))/(cw*sw), 0}},

C[ S[1] , V[5] , V[2] ] == {{(I*CH*EL*(cw^2 + sw^2)*vev)/(cw*sw), 0}},

C[ -F[13] , F[13] , V[1] ] == {{0, 0}, {0, 0}, {(-I)*CMB*cw, 0}, {(-I)*CMB*cw, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*CMB*cw, 0}, {I*CMB*cw, 0}},

C[ -F[13] , F[13] , V[2] ] == {{0, 0}, {0, 0}, {I*CMB*sw, 0}, {I*CMB*sw, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(-I)*CMB*sw, 0}, {(-I)*CMB*sw, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc133, 0}, {I*gc133, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc134, 0}, {I*gc134, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc135, 0}, {I*gc135, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc136*IndexDelta[e1x2, e2x2], 0}, {I*gc136*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc137*IndexDelta[e1x2, e2x2], 0}, {I*gc137*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc138*IndexDelta[e1x2, e2x2], 0}, {I*gc138*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc139*IndexDelta[e1x2, e2x2], 0}, {I*gc139*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc140*IndexDelta[e1x2, e2x2], 0}, {I*gc140*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc141*IndexDelta[e1x2, e2x2], 0}, {I*gc141*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc142*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc142*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc143*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc143*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc144*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc144*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc145*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc145*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc146*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc146*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc147*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc147*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc148*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc149*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc150*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc151*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc152*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc153*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc154*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc155*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc156*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc157*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc158*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc159*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc160*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc161*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc162*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc163*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc164*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc165*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc166, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc167, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc168, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc169, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc170, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc171, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc172L*IndexDelta[e1x2, e2x2], 0}, {I*gc172R*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc173L*IndexDelta[e1x2, e2x2], 0}, {I*gc173R*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc174L*IndexDelta[e1x2, e2x2], 0}, {I*gc174R*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc175L*IndexDelta[e1x2, e2x2], 0}, {I*gc175R*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc176L*IndexDelta[e1x2, e2x2], 0}, {I*gc176R*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc177L*IndexDelta[e1x2, e2x2], 0}, {I*gc177R*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc178, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc179, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc180, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc181L, 0}, {I*gc181R, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc182L, 0}, {I*gc182R, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc183L, 0}, {I*gc183R, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[5] ] == {{I*gc184L*IndexDelta[e1x2, e2x2], 0}, {I*gc184R*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[5] ] == {{I*gc185L*IndexDelta[e1x2, e2x2], 0}, {I*gc185R*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[5] ] == {{I*gc186L*IndexDelta[e1x2, e2x2], 0}, {I*gc186R*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[5] ] == {{I*gc187L*IndexDelta[e1x2, e2x2], 0}, {I*gc187R*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[10, {e2x2}] , V[5] ] == {{I*gc188*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[11, {e2x2}] , V[5] ] == {{I*gc189*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[12, {e2x2}] , V[5] ] == {{I*gc190*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[5] ] == {{I*gc191L*IndexDelta[e1x2, e2x2], 0}, {I*gc191R*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[11, {e2x2}] , V[5] ] == {{I*gc192*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[12, {e2x2}] , V[5] ] == {{I*gc193*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[10, {e2x2}] , V[5] ] == {{I*gc194*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[5] ] == {{I*gc195L*IndexDelta[e1x2, e2x2], 0}, {I*gc195R*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1] , F[1] , V[5] ] == {{I*gc196, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2] , F[2] , V[5] ] == {{I*gc197, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[3] , F[3] , V[5] ] == {{I*gc198, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4] , F[4] , V[5] ] == {{I*gc199L, 0}, {I*gc199R, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[5] , F[5] , V[5] ] == {{I*gc200L, 0}, {I*gc200R, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[6] , F[6] , V[5] ] == {{I*gc201L, 0}, {I*gc201R, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc12 -> -CH,
     gc13 -> -EL,
     gc14 -> CH,
     gc15 -> EL,
     gc16 -> -EL,
     gc18 -> EL,
     gc21 -> -EL,
     gc22 -> -((cw*EL)/sw),
     gc24 -> (cw*EL)/sw,
     gc26 -> -EL,
     gc29 -> EL,
     gc30 -> (cw*EL)/sw,
     gc32 -> -((cw*EL)/sw),
     gc34 -> (cw*EL)/sw,
     gc36 -> -((cw*EL)/sw),
     gc41L -> -((CP - CS)*vev),
     gc41R -> (CP + CS)*vev,
     gc42 -> GS,
     gc43 -> -GS,
     gc44 -> -GS^2,
     gc45L -> -CA + CV,
     gc45R -> CA + CV,
     gc46L -> yb*Conjugate[CKM2x3],
     gc46R -> -(yc*Conjugate[CKM2x3]),
     gc47L -> yb*Conjugate[CKM3x3],
     gc47R -> -(yt*Conjugate[CKM3x3]),
     gc48L -> yb*Conjugate[CKM1x3],
     gc48R -> -(yup*Conjugate[CKM1x3]),
     gc49L -> ydo*Conjugate[CKM2x1],
     gc49R -> -(yc*Conjugate[CKM2x1]),
     gc50L -> ydo*Conjugate[CKM3x1],
     gc50R -> -(yt*Conjugate[CKM3x1]),
     gc51L -> ydo*Conjugate[CKM1x1],
     gc51R -> -(yup*Conjugate[CKM1x1]),
     gc52L -> ys*Conjugate[CKM2x2],
     gc52R -> -(yc*Conjugate[CKM2x2]),
     gc53L -> ys*Conjugate[CKM3x2],
     gc53R -> -(yt*Conjugate[CKM3x2]),
     gc54L -> ys*Conjugate[CKM1x2],
     gc54R -> -(yup*Conjugate[CKM1x2]),
     gc55L -> -(yb/Sqrt[2]),
     gc55R -> yb/Sqrt[2],
     gc56L -> -(ydo/Sqrt[2]),
     gc56R -> ydo/Sqrt[2],
     gc57L -> -(ys/Sqrt[2]),
     gc57R -> ys/Sqrt[2],
     gc58 -> -(yb/Sqrt[2]),
     gc59 -> -(ydo/Sqrt[2]),
     gc60 -> -(ys/Sqrt[2]),
     gc61 -> ye,
     gc62 -> ym,
     gc63 -> ytau,
     gc64L -> -(ye/Sqrt[2]),
     gc64R -> ye/Sqrt[2],
     gc65L -> -(ym/Sqrt[2]),
     gc65R -> ym/Sqrt[2],
     gc66L -> -(ytau/Sqrt[2]),
     gc66R -> ytau/Sqrt[2],
     gc67 -> -(ye/Sqrt[2]),
     gc68 -> -(ym/Sqrt[2]),
     gc69 -> -(ytau/Sqrt[2]),
     gc70L -> CKM2x3*yc,
     gc70R -> -(CKM2x3*yb),
     gc71L -> CKM2x1*yc,
     gc71R -> -(CKM2x1*ydo),
     gc72L -> CKM2x2*yc,
     gc72R -> -(CKM2x2*ys),
     gc73L -> CKM3x3*yt,
     gc73R -> -(CKM3x3*yb),
     gc74L -> CKM3x1*yt,
     gc74R -> -(CKM3x1*ydo),
     gc75L -> CKM3x2*yt,
     gc75R -> -(CKM3x2*ys),
     gc76L -> CKM1x3*yup,
     gc76R -> -(CKM1x3*yb),
     gc77L -> CKM1x1*yup,
     gc77R -> -(CKM1x1*ydo),
     gc78L -> CKM1x2*yup,
     gc78R -> -(CKM1x2*ys),
     gc79L -> yc/Sqrt[2],
     gc79R -> -(yc/Sqrt[2]),
     gc80L -> yt/Sqrt[2],
     gc80R -> -(yt/Sqrt[2]),
     gc81L -> yup/Sqrt[2],
     gc81R -> -(yup/Sqrt[2]),
     gc82 -> -(yc/Sqrt[2]),
     gc83 -> -(yt/Sqrt[2]),
     gc84 -> -(yup/Sqrt[2]),
     gc88 -> EL/(2*sw),
     gc89 -> -EL/(2*sw),
     gc90 -> EL,
     gc97 -> -EL/(2*sw),
     gc98 -> -EL/(2*sw),
     gc103 -> -EL^2,
     gc104 -> (cw*EL)/sw,
     gc105 -> EL^2/sw^2,
     gc109R -> -ye,
     gc110R -> -ym,
     gc111R -> -ytau,
     gc113 -> -(EL*(cw^2 + sw^2))/(2*cw*sw),
     gc114 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc121 -> (cw*EL^2)/sw,
     gc126 -> -((cw^2*EL^2)/sw^2),
     gc133 -> -EL,
     gc134 -> -EL,
     gc135 -> -EL,
     gc136 -> (2*EL)/3,
     gc137 -> (2*EL)/3,
     gc138 -> (2*EL)/3,
     gc139 -> -EL/3,
     gc140 -> -EL/3,
     gc141 -> -EL/3,
     gc142 -> GS,
     gc143 -> GS,
     gc144 -> GS,
     gc145 -> GS,
     gc146 -> GS,
     gc147 -> GS,
     gc148 -> (CKM2x3*EL)/(Sqrt[2]*sw),
     gc149 -> (CKM2x1*EL)/(Sqrt[2]*sw),
     gc150 -> (CKM2x2*EL)/(Sqrt[2]*sw),
     gc151 -> (CKM3x3*EL)/(Sqrt[2]*sw),
     gc152 -> (CKM3x1*EL)/(Sqrt[2]*sw),
     gc153 -> (CKM3x2*EL)/(Sqrt[2]*sw),
     gc154 -> (CKM1x3*EL)/(Sqrt[2]*sw),
     gc155 -> (CKM1x1*EL)/(Sqrt[2]*sw),
     gc156 -> (CKM1x2*EL)/(Sqrt[2]*sw),
     gc157 -> (EL*Conjugate[CKM2x3])/(Sqrt[2]*sw),
     gc158 -> (EL*Conjugate[CKM3x3])/(Sqrt[2]*sw),
     gc159 -> (EL*Conjugate[CKM1x3])/(Sqrt[2]*sw),
     gc160 -> (EL*Conjugate[CKM2x1])/(Sqrt[2]*sw),
     gc161 -> (EL*Conjugate[CKM3x1])/(Sqrt[2]*sw),
     gc162 -> (EL*Conjugate[CKM1x1])/(Sqrt[2]*sw),
     gc163 -> (EL*Conjugate[CKM2x2])/(Sqrt[2]*sw),
     gc164 -> (EL*Conjugate[CKM3x2])/(Sqrt[2]*sw),
     gc165 -> (EL*Conjugate[CKM1x2])/(Sqrt[2]*sw),
     gc166 -> EL/(Sqrt[2]*sw),
     gc167 -> EL/(Sqrt[2]*sw),
     gc168 -> EL/(Sqrt[2]*sw),
     gc169 -> EL/(Sqrt[2]*sw),
     gc170 -> EL/(Sqrt[2]*sw),
     gc171 -> EL/(Sqrt[2]*sw),
     gc172L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc172R -> (-2*EL*sw)/(3*cw),
     gc173L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc173R -> (-2*EL*sw)/(3*cw),
     gc174L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc174R -> (-2*EL*sw)/(3*cw),
     gc175L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc175R -> (EL*sw)/(3*cw),
     gc176L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc176R -> (EL*sw)/(3*cw),
     gc177L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc177R -> (EL*sw)/(3*cw),
     gc178 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc179 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc180 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc181L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc181R -> (EL*sw)/cw,
     gc182L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc182R -> (EL*sw)/cw,
     gc183L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc183R -> (EL*sw)/cw,
     gc184L -> Cq2,
     gc184R -> Cu2,
     gc185L -> Cq3,
     gc185R -> Cu3,
     gc186L -> Cq1,
     gc186R -> Cu1,
     gc187L -> CKM1x3*Cq1*Conjugate[CKM1x3] + CKM2x3*Cq2*Conjugate[CKM2x3] + CKM3x3*Cq3*Conjugate[CKM3x3],
     gc187R -> Cd3,
     gc188 -> CKM1x1*Cq1*Conjugate[CKM1x3] + CKM2x1*Cq2*Conjugate[CKM2x3] + CKM3x1*Cq3*Conjugate[CKM3x3],
     gc189 -> CKM1x2*Cq1*Conjugate[CKM1x3] + CKM2x2*Cq2*Conjugate[CKM2x3] + CKM3x2*Cq3*Conjugate[CKM3x3],
     gc190 -> CKM1x3*Cq1*Conjugate[CKM1x1] + CKM2x3*Cq2*Conjugate[CKM2x1] + CKM3x3*Cq3*Conjugate[CKM3x1],
     gc191L -> CKM1x1*Cq1*Conjugate[CKM1x1] + CKM2x1*Cq2*Conjugate[CKM2x1] + CKM3x1*Cq3*Conjugate[CKM3x1],
     gc191R -> Cd1,
     gc192 -> CKM1x2*Cq1*Conjugate[CKM1x1] + CKM2x2*Cq2*Conjugate[CKM2x1] + CKM3x2*Cq3*Conjugate[CKM3x1],
     gc193 -> CKM1x3*Cq1*Conjugate[CKM1x2] + CKM2x3*Cq2*Conjugate[CKM2x2] + CKM3x3*Cq3*Conjugate[CKM3x2],
     gc194 -> CKM1x1*Cq1*Conjugate[CKM1x2] + CKM2x1*Cq2*Conjugate[CKM2x2] + CKM3x1*Cq3*Conjugate[CKM3x2],
     gc195L -> CKM1x2*Cq1*Conjugate[CKM1x2] + CKM2x2*Cq2*Conjugate[CKM2x2] + CKM3x2*Cq3*Conjugate[CKM3x2],
     gc195R -> Cd2,
     gc196 -> Cl1,
     gc197 -> Cl2,
     gc198 -> Cl3,
     gc199L -> Cl1,
     gc199R -> Ce1,
     gc200L -> Cl2,
     gc200R -> Ce2,
     gc201L -> Cl3,
     gc201R -> Ce3};

